[package]
name = "gmusic"
version = "0.1.0"
authors = ["Max Jööhnk <maxjoehnk@gmail.com>"]

[dependencies]
env_logger = "0.4.3"
log = "0.4.1"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_urlencoded = "0.5.1"
serde_ini = "0.1.3"
reqwest = "0.8.2"
url = "1.6.0"
mime = "*"
rand = "*"
base64 = "0.9.0"
sha1 = "0.4.0"
byteorder = "1.2.1"
openssl = "0.9.23"
hyper = "0.11.9"