[package]
name = "gmusic"
version = "0.1.0"
authors = ["Max Jöhnk <maxjoehnk@gmail.com>"]
edition = "2018"

[dependencies]
log = "0.4"
serde = "1"
serde_derive = "1"
serde_json = "1"
serde_urlencoded = "0.6"
serde_ini = "0.2"
reqwest = "0.9"
url = "2.1.0"
mime = "0.3"
rand = "0.7"
base64 = "0.11"
sha1 = "0.6"
byteorder = "1.3.2"
openssl = "0.10.26"
hyper = "0.12"